from base import Peripheral
from ports import IO_Port
from meshGen import Block

class BlockRam(Peripheral):
    blockGrid= [
        [
            [ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
            [ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
            [ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone ,Block.coalOre, Block.stone , Block.stone , ],
    		[ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone ,Block.coalOre,Block.coalOre, Block.stone , ],
    		[ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone ,Block.coalOre,Block.coalOre, Block.stone , ],
    		[ Block.stone , Block.stone , Block.stone , Block.stone , Block.sand  , Block.sand  , Block.sand  , Block.sand  , ],
        ],
        [
    		[ Block.stone , Block.stone ,Block.ironOre, Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.stone , Block.stone ,Block.ironOre,Block.ironOre, Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.grass , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.grass , Block.grass , Block.grass , Block.stone ,Block.coalOre,Block.coalOre,Block.coalOre, Block.stone , ],
    		[ Block.grass , Block.grass , Block.dirt  , Block.grass , Block.stone , Block.sand  ,Block.coalOre, Block.stone , ],
    		[ Block.grass , Block.grass , Block.grass , Block.grass , Block.grass , Block.sand  , Block.sand  , Block.sand  , ],
    		[ Block.grass , Block.grass , Block.grass , Block.grass , Block.sand  , Block.sand  , Block.sand  , Block.sand  , ],
        ],
        [
    		[ Block.stone , Block.stone ,Block.ironOre,Block.ironOre, Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.stone , Block.stone , Block.stone ,Block.ironOre, Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.grass , Block.grass , Block.stone , Block.stone , Block.stone , Block.stone ,Block.ironOre,Block.ironOre, ],
    		[ Block.air   , Block.grass , Block.grass , Block.grass , Block.stone , Block.stone , Block.stone ,Block.ironOre, ],
    		[ Block.air   , Block.air   , Block.air   , Block.grass , Block.grass , Block.stone , Block.stone , Block.stone , ],
    		[ Block.air   , Block.air   , Block.log   , Block.air   , Block.grass , Block.sand  , Block.sand  , Block.sand  , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.sand  , Block.sand  , Block.sand  , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
        ],
        [
    		[ Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.grass , Block.grass , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.air   , Block.air   , Block.grass , Block.grass , Block.stone , Block.stone ,Block.ironOre,Block.ironOre, ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.grass , Block.stone , Block.sand  ,Block.ironOre, ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.grass , Block.sand  , Block.sand  , ],
    		[ Block.air   , Block.air   , Block.log   , Block.air   , Block.air   , Block.air   , Block.sand  , Block.sand  , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
        ],
        [
    		[ Block.grass , Block.grass , Block.grass , Block.stone , Block.stone , Block.stone , Block.stone , Block.stone , ],
    		[ Block.air   , Block.air   , Block.grass , Block.grass , Block.grass , Block.stone , Block.stone , Block.sand  , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.grass , Block.grass , Block.stone , Block.sand  , ],
    		[ Block.air   , Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.grass , Block.sand  , Block.sand  , ],
    		[ Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.sand  , Block.sand  , ],
    		[ Block.leaves, Block.leaves, Block.log   , Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , ],
    		[ Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , Block.air   , ],
        ],
		[
    		[ Block.air   , Block.air   , Block.air   , Block.grass , Block.grass , Block.grass , Block.grass , Block.grass , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.grass , Block.grass , Block.sand  , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.grass , Block.sand  , ],
    		[ Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , Block.sand  , ],
    		[ Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , ],
    		[ Block.leaves, Block.leaves, Block.log   , Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , ],
    		[ Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , Block.air   , ],
        ],
        [
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
        ],
        [
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.leaves, Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.leaves, Block.leaves, Block.leaves, Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.leaves, Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
    		[ Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , Block.air   , ],
        ]
    ]